# This file has been added on OGCIO fork
services:
  postgres:
    image: postgres:14-alpine
    user: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p0stgr3s
      PGPORT: 5433
      POSTGRES_DB: logto
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5433:5433

volumes:
  db:
    driver: local
