# OGCIO

variables:
  awsServiceConnection: aws-sharedservices-building-blocks-azure-devops
  awsRegion: eu-west-1
  ecrEndpoint: 428528001781.dkr.ecr.eu-west-1.amazonaws.com
  buildArguments: ""
  environment: LifeEvents-dev
  clusterName: non-prod-02
  # E2E Test Configuration
  OGCIO_TEST_USERNAME: $(TEST_USERNAME_DEV)
  OGCIO_TEST_PASSWORD: $(TEST_PASSWORD_DEV)
